# Generated by Django 2.2 on 2019-04-22 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0002_auto_20190422_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='remaining_invitation',
            new_name='remaining_invitations',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='used_invitatios',
            new_name='used_invitations',
        ),
    ]
